"""
Nexus AI — Node 2: ContextRetriever Agent
Retrieves personal memories and collective knowledge insights via pgvector.
"""

import structlog
from app.agents.state import WorkflowState
from app.services.memory_service import MemoryService
from app.models.user import UserIdentity

logger = structlog.get_logger()


async def context_retriever_node(state: WorkflowState) -> dict:
    """Node 2 — Retrieve personal memories, collective knowledge insights, and user identity."""
    logger.info("context_retriever_start", user_id=state.user_id)

    memory_service = MemoryService()

    # Fetch user identity
    identity_data = await memory_service.get_user_identity(state.user_id)
    user_identity = None
    if identity_data:
        user_identity = UserIdentity(**identity_data)

    # Use the optimized search query generated by the Perceiver (fallback to raw message)
    search_query = state.search_query or state.user_message

    # Search personal memories
    personal_memories = await memory_service.search_personal_memories(
        user_id=state.user_id,
        query=search_query,
    )

    # If vector search returned too few, supplement with recent memories
    if len(personal_memories) < 2:
        recent = await memory_service.get_recent_memories(state.user_id, limit=3)
        existing_ids = {m.memory.id for m in personal_memories}
        from app.models.memory import MemorySearchResult
        for mem in recent:
            if mem.id not in existing_ids:
                personal_memories.append(
                    MemorySearchResult(memory=mem, similarity_score=0.0)
                )

    # Search collective knowledge
    collective_knowledge = await memory_service.search_collective_knowledge(
        query=search_query,
    )

    logger.info(
        "context_retriever_complete",
        personal_count=len(personal_memories),
        collective_count=len(collective_knowledge),
        has_identity=user_identity is not None,
    )

    return {
        "user_identity": user_identity,
        "personal_memories": personal_memories,
        "collective_knowledge": collective_knowledge,
    }
